name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run: |
          url="$(wget -qO - https://api.github.com/repos/jgm/pandoc/releases/latest | tr '"' '\n' | grep '.*/download/.*-amd64.deb')"
          filename="pandoc-latest-amd64.deb"
          wget -O "$filename" "$url"
          sudo dpkg -i "$filename"
      - name: Echo the greeting's time
        run: pwd && ls
      - name: Build PDF files
        run: |
          for mdfile in *.md
          do
            pandoc "$mdfile" -o "$mdfile.pdf"
          done
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: .
