name: Build PDF files (workflow)
on: [push]

jobs:
  build:
    name: Build PDF files (job)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeX Live and pandoc
        run: |
          temp="$(mktemp -d)"
          url=http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          wget -qO - "$url" | tar --strip-components=1 -C "$temp" -xzvf -
          scheme="scheme-basic"
          printf '%s\n' "selected_scheme $scheme" "instopt_adjustpath 1" | tee -a "$temp/texlive.profile"
          (cd "$temp" && sudo ./install-tl -profile texlive.profile)
          sudo tlmgr install xcolor
          url=https://api.github.com/repos/jgm/pandoc/releases/latest
          url="$(wget -qO - "$url" | tr '"' '\n' | grep '.*/download/.*-amd64.deb')"
          filename="$temp/pandoc-latest-amd64.deb"
          wget -O "$filename" "$url"
          sudo dpkg -i "$filename"
      - name: Build PDF files
        run: |
          mkdir build
          for mdfile in *.md
          do
            pandoc "$mdfile" -o "build/$(basename "$mdfile" .md).pdf"
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: PDF files
          path: build
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          hub release delete latest
          hub release create --copy -a build/*.pdf -m "Latest release" -m "$GITHUB_REF" latest
