on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:buster
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y python3
          python3 -c 'print("hello")'
